name: MaskUI
version: 1.3.2
main: SkulZOnTheYT\MaskUI\Main
api: 5.0.0
depend: BedrockEconomy
softdepend: FormImagesFix
author: SkulZOnTheYT, Kylan1940

commands:
  mask:
   description: "open mask ui"
   permission: "maskui-open.commands"
   
permissions:
  maskui-open.commands:
   description: "allow user open mask ui"
   default: true
